### PR TITLE
Fixes to SGIP1 example, standalone housing generator function

### PR DESCRIPTION
**Pull request by temcdrm**
Fixes for:

- [SGIP1 load oscillations](https://github.com/pnnl/tesp/issues/46)
- [SGIP1 HVAC Bids](https://github.com/pnnl/tesp/issues/43)
- [SGIP1 EnergyPlus prices](https://github.com/pnnl/tesp/issues/45)

Also has the preliminary version of a separate function that writes houses for a specific node, for CEF2 project.

### CODE REVIEW

**Comment by trevorhardy** [comment]
@temcdrm: Since I've installed TESP via the installer, how do I get these changes into my installation to test?

**Comment by temcdrm** [comment]
I think you can do that with <= 10 hand-edits from the last two commits:

- gridlabdSimulator1 ==> gld1 in 5 or 6 SGIP1*.glm files
- substation ==> sub1 in a yaml file
- player ==> sub1 in another yaml file

**Comment by temcdrm** [comment]
you don't need the change to api.py in the last commit

**Comment by trevorhardy** [comment]
I tested SGIP1c with the changes made and using the default `plots.py` I'm still seeing a flat price in the EnergyPlus plots. Is that working for you, @temcdrm?

**Comment by temcdrm** [comment]
Yes, it's working for me on SGIP1b.  This is the key change: https://github.com/pnnl/tesp/pull/48/commits/17a286fe06770e2dd305c27598aad01bef74dc5b

There should be no difference with SGIP1c or the others, because they share the same yaml file.

**Comment by temcdrm** [comment]
There are only two variants of FNCS_Config.txt, one for A and one for B.  For C, D, E the differences are in DER, not controllers.

**Comment by trevorhardy** [comment]
@temcdrm, let me know when you're ready to consider this PR complete and we'll review and merge it. From the original commits I've been able to verify the fixes you've put in place so I think we're good so far.

**Comment by temcdrm** [comment]
This is ready to review and merge

**Comment by laurmarinovici** [comment]
Is this latest code review, for SGIP1 example running on a FNCS-based TESP or HELICS-based? I currently do not have a FNCS-based one, and I am not up to date with what works and what not version-wise.

**Comment by temcdrm** [comment]
Probably FNCS, but the configurable version should also work with HELICS.  See examples/comm/make_comm_base.py, where it configures from SGIP1c.json

**Review by trevorhardy — APPROVED** [review]

**Review by trevorhardy — APPROVED** [review]

**Comment by temcdrm** [comment]
Trevor & Laurentiu - should I go ahead and merge this?

**Comment by laurmarinovici** [comment]
@temcdrm Is there a latest version of docker I could use? I tried running the prepare_cases.py in sgip example inside my docker container, but I do not have the correct environment variables and paths, which results in error; see:
```
Traceback (most recent call last):
  File "prepare_cases.py", line 5, in <module>
    tmy_file = os.getenv('TESP_INSTALL') + '/share/support/weather/AZ-Tucson_International_Ap.tmy3'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
On Docker hub I could only find docker pull temcderm/tesp_core:1.0.1, which seems to be from 7 months ago, and up to path 1 compared to patch 2 in the release.

I have also tried to install release v1.0.2 on an ubuntu 20.4 docker, but I got this error

```
Installing
 0% ______________ 50% ______________ 100%
 
Error: There has been an error.
Error running apt-get -y install coinor-cbc: E: Unable to locate package 
coinor-cbc
```

**Review by laurmarinovici — APPROVED** [review]

**Review by laurmarinovici — APPROVED** [review]

**Comment by temcdrm** [comment]
I've updated the two Dockerfiles for 1.0.2.  One change was caused by removal of ```apt-utils``` from the package repository; not sure why, and the first docker build throws a warning but runs to completion.  I also had to run ```apt update``` twice within the image for tesp_foundation; not sure why.

**Pull request merged**
