### PR TITLE
Merge branch 'evolve' into sgip1_doc

### PR DESCRIPTION
**Pull request by trevorhardy**
* evolve: (68 commits)
  More edits for dsot integration to TESP...
  More edits for dsot integration to TESP
  Deleted another WANT_VI_DUMP from glm
  Deleted WANT_VI_DUMP from glm
  More edits for restructure install
  More edits for restructure install and dsot
  Setup environment variable for scripts
  Replace necessary model parameter
  Add reference implementation for simple_auction and a bit of documentation
  Update gitignore for PyCharm project
  More updates on paths restructuring
  Update TESP install script files
  Updating back port of DSOT
  Update installing scripts....'
  Update installing scripts....'
  Update installing scripts....'
  Update installing scripts...'
  Update installing scripts...
  Fixing clean.sh scripts, compling scripts
  Update installing scripts..
  ...

# Conflicts:
#	.gitignore
#	install/Linux/helpers/clean_outputs.sh
#	src/tesp_support/tesp_support/process_agents.py
#	src/tesp_support/tesp_support/process_eplus.py
#	src/tesp_support/tesp_support/process_gld.py
#	src/tesp_support/tesp_support/process_houses.py
#	src/tesp_support/tesp_support/process_inv.py
#	src/tesp_support/tesp_support/process_pypower.py

### CODE REVIEW

**Comment by trevorhardy** [comment]
I think I resolved the conflicts succesfully in the `process_x.py` but @d3j331, you'll probably want to take a look.

**Review by d3j331 — COMMENTED** [review]
process_gld.py : lines 570-571 should be used

**Comment by trevorhardy** [comment]
I'm not seeing lines 570-571 commented out in process_gld.py (in [sgip1_doc](https://github.com/pnnl/tesp/blob/e3ec589bbd9cb90648613898ebc0da9cc883e9bb/src/tesp_support/tesp_support/process_gld.py#L570) or [evolve](https://github.com/pnnl/tesp/blob/b0564b2ecb290d341a302c5edd98d5d7a44af3f7/src/tesp_support/tesp_support/process_gld.py#L570)). Can you double-check what you're seeing?

**Comment by d3j331** [comment]
From github pull request

***@***.***

New arg -> 'path' in the call

def read_gld_metrics (path, nameroot, dictname = ''):

Also in the glm_dict.py seems little funky, I believe all the metrics types should be there.
Maybe we need a call to resolve.

Mitch

**Comment by trevorhardy** [comment]
Re-attempting this in a fresh sets of merges.

**Pull request closed without merging**
